### PR TITLE
Courtney

### PR DESCRIPTION
**Pull request by clburns107**

### CODE REVIEW

**Comment by clburns107** [comment]
I guess im not even sure where to start with this.  I get the flow of how the servers talk to each other but Im not sure what angel to start from...

**Comment by halfghaninne** [comment]
I found setting up the HTML according to the instructions and then corresponding variables in my JS to be a good starting point.

Then I focused on building the JS functionality and corresponding Ruby controller actions to get back **one** question from the DB.

**Comment by clburns107** [comment]
the instructions for part one say to just use the button thats there. Im particularly confused about where the event listener should go.  if it goes on the XHR object how does the button know thats its clicked? If it goes on the button how does the XHR object get opened?

**Comment by halfghaninne** [comment]
I'm sorry that's my bad. I skipped to the Phase 2 instructions.  Following up...

**Comment by halfghaninne** [comment]
So you will have nested EventListeners! You can have one on the button that's already there, that is in charge of preparing and sending some request...

And then, inside that, an EventListener that does some work once the request is loaded.

**Comment by clburns107** [comment]
So where does this get sent to on the server? a controller? which sends back an erb? and whats on the erb? literally just text? do we put it in html? can we use ruby in that erb? is there a map of how the actual files talk to each other? i did see the map of how the servers talk but im just really need a visual for the files.

**Comment by clburns107** [comment]
Also if your "/" controller is requesting local host 9292 how does the front end know that "/" is actually 8080?

**Comment by halfghaninne** [comment]
How the files on the server-side talk to one another should feel very familiar; it's just the same as the projects we've been working with in Sinatra.

The difference now is that we have a **client-side server** making the requests to our **server-side controller**. So the responses that are served up from a controller action (the erb files) can be thought of as the `responseText` of our request on the client-side.

**Comment by halfghaninne** [comment]
As far as what is in the erb, TIAS.

**Comment by halfghaninne** [comment]
Your **client-side** server on port 8080 will be making requests to the **server-side** server on port 9292

**Pull request closed without merging**
